// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorWASMAndAzureSql.Server.databases.models
{
    public partial class Peoples
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal? Height { get; set; }
        public int? Mass { get; set; }
        public string HairColor { get; set; }
        public string SkinColor { get; set; }
        public string EyeColor { get; set; }
        public string BirthYear { get; set; }
        public string Gender { get; set; }
        public string Url { get; set; }
        public int? PlanetId { get; set; }
    }
}