// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorWASMAndAzureSql.Server.databases.models
{
    public partial class Planets
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? RotationPeriod { get; set; }
        public int? OrbitalPeriod { get; set; }
        public int? Diameter { get; set; }
        public string Climate { get; set; }
        public string Gravity { get; set; }
        public string Terrain { get; set; }
        public string SurfaceWater { get; set; }
        public int? Population { get; set; }
        public string Url { get; set; }
    }
}