// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorWASMAndAzureSql.Server.databases.models
{
    public partial class RefPlanetSpecies
    {
        public int Id { get; set; }
        public int? PlanetId { get; set; }
        public int? SpeciesId { get; set; }
    }
}